from pathlib import Path
from unittest import TestCase

from camera_tracking.config import load_config


class ConfigTest(TestCase):
    def test_load_config(self) -> None:
        config = load_config(Path("config/default.yaml"))

        self.assertEqual(config.camera.source, 0)
        self.assertEqual(config.detection.model_path, "yolo26s.engine")
        self.assertEqual(config.detection.confidence_threshold, 0.25)
        self.assertEqual(config.detection.image_size, 640)
        self.assertEqual(config.detection.nms_iou_threshold, 0.85)
        self.assertEqual(config.tracking.min_hits, 3)
        self.assertEqual(config.tracking.track_high_threshold, 0.50)
        self.assertEqual(config.tracking.track_low_threshold, 0.10)
        self.assertEqual(config.tracking.new_track_threshold, 0.60)
        self.assertEqual(config.tracking.byte_match_threshold, 0.80)
        self.assertEqual(config.tracking.track_buffer, 90)
        self.assertEqual(config.identity.match_threshold, 0.70)
        # Chong swap ID khi 2 nguoi di qua nhau: appearance quyet dinh,
        # spatial chi phu.
        self.assertEqual(config.identity.appearance_weight, 0.70)
        self.assertEqual(config.identity.spatial_weight, 0.05)
        self.assertEqual(
            config.identity.same_camera_reconnect_distance_ratio, 0.06)
        self.assertEqual(config.identity.min_appearance_similarity, 0.70)
        self.assertEqual(config.identity.named_appearance_floor, 0.70)
        self.assertEqual(config.identity.active_duplicate_similarity, 0.90)
        self.assertEqual(config.identity.gallery_refresh_steps, 10)
        self.assertEqual(config.identity.reid_model, "osnet_x0_25")
        self.assertEqual(config.identity.tentative_min_hits, 5)
        self.assertEqual(config.face.match_threshold, 0.45)
        self.assertEqual(config.face.min_margin, 0.05)
        self.assertEqual(config.face.consensus_hits, 1)
        self.assertEqual(config.face.min_blur_variance, 8.0)
        self.assertEqual(config.face.det_size, 640)
        self.assertEqual(config.face.min_face_score, 0.35)
        self.assertEqual(config.face.min_person_area_px, 2500.0)
        self.assertEqual(list(config.face.channels), ["A", "B"])
        self.assertEqual(config.face.face_device, "cuda")
        self.assertEqual(config.attendance.debounce_hits, 1)
        self.assertEqual(config.room_fusion.inroom_min_interval_s, 600.0)
        self.assertEqual(config.room_fusion.absent_fallback_s, 900.0)
        self.assertEqual(config.workstations, [])
        self.assertEqual(config.workstate.grace_s, 1.5)
        self.assertEqual(config.workstate.move_ratio, 0.0)
        self.assertEqual(config.voice.backend, "imou_p2p")
        self.assertEqual(config.voice.command_ttl_s, 10.0)
        self.assertEqual(config.voice.proactive_quiet_s, 5.0)
        self.assertEqual(config.voice.bridge_port, 8767)
        self.assertEqual(config.voice.p2p_channel, 1)
        self.assertEqual(config.voice.p2p_channel_b, 2)
        self.assertEqual(config.voice.p2p_sample_rate, 16000)
        self.assertEqual(config.voice.palm_min_detection_confidence, 0.35)
        self.assertEqual(config.voice.palm_required_fingers, 4)
        self.assertEqual(config.voice.palm_min_input_height_px, 320)
        self.assertEqual(config.voice.palm_confirm_frames, 1)
        self.assertEqual(config.voice.palm_face_ttl_s, 8.0)
        # Wave: foreground on dinh + 5 ngon xoe truoc khi dem dao chieu.
        self.assertEqual(config.voice.wave_min_reversals, 2)
        self.assertEqual(config.voice.wave_required_fingers, 5)
        self.assertEqual(config.voice.wave_palm_confirm_frames, 2)
        self.assertEqual(config.voice.wave_palm_release_frames, 5)
        self.assertEqual(config.voice.focus_switch_area_ratio, 1.20)
        self.assertEqual(config.voice.focus_switch_hold_s, 0.50)
        self.assertEqual(config.voice.focus_lost_grace_s, 1.00)
        self.assertEqual(config.voice.face_frontal_nose_tol, 0.18)
        self.assertEqual(config.voice.face_frontal_roll_tol, 0.18)
        self.assertEqual(config.voice.face_frontal_min_eye_ratio, 0.20)
        # Chao khach la hoan 2s cho dinh danh (chi chao ten neu kip).
        self.assertEqual(config.voice.unknown_greet_delay_s, 2.0)
        self.assertEqual(config.voice.face_max_queue, 8)
        self.assertEqual(config.voice.face_max_job_age_s, 5.0)
        # Hearing chong nhiem phong on: cum goi tu folder, VAD dong, SNR, STT siet.
        self.assertEqual(config.voice.voice_trigger_words, [])
        self.assertEqual(config.voice.voice_face_ttl_s, 3.0)
        self.assertEqual(config.voice.voice_vad_floor_factor, 3.0)
        self.assertEqual(config.voice.voice_snr_min_db, 10.0)
        self.assertEqual(config.voice.voice_max_no_speech_prob, 0.40)
        self.assertEqual(config.voice.voice_min_avg_logprob, -0.90)
        self.assertEqual(len(config.analytics.calibration.image_points), 4)
